name: lambs
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.5
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2023.12.12
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cryptography=41.0.7
  - gtts=2.5.0
  - idna=3.4
  - intel-openmp=2023.1.0
  - libcxx=14.0.6
  - libffi=3.4.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.3
  - numpy-base=1.26.3
  - openssl=3.0.12
  - pandas=2.1.1
  - pip=23.3.1
  - pycparser=2.21
  - pyopenssl=23.2.0
  - pysocks=1.7.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - pytz=2023.3.post1
  - readline=8.2
  - requests=2.28.1
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tk=8.6.12
  - tzdata=2023d
  - urllib3=1.26.18
  - wheel=0.41.2
  - xz=5.4.5
  - zlib=1.2.13
