name: Continuous Integration

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Getting Git Commit ID
      id: get_id
      run: |
        COMMIT_ID=$(git rev-parse HEAD)
        echo "commit_id=$COMMIT_ID" >> "$GITHUB_OUTPUT"
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: lambs:${{ steps.get_id.outputs.commit_id }}
        outputs: type=docker,dest=/tmp/lambs.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: lambs
        path: /tmp/lambs.tar