name: Continuous Integration

on: workflow_dispatch

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: actions/checkout@v4
    - name: Building Docker Image
      run: docker build -t lambs:test .