name: Continious Integration

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: lambs
        environment-file: environment.yml
    - name: Conda list
      shell: bash
      run: conda list